Turnos/Models/Especialidad.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Turnos.Models
{
    public class Especialidad
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage ="Debe ingresar una descripcion"),StringLength(200, ErrorMessage ="El campo solo acepta 200 caracteres como maximo")]
        public string? Descripcion { get; set; } 

        public List<MedicoEspecialidad>? MedicoEspecialidad { get; set; }    
    }
}

Turnos/Controllers/EspecialidadController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.FileProviders;
using Turnos.Models;

namespace Turnos.Controllers
{
    public class EspecialidadController : Controller
    {

        private readonly TurnosContext _turnosContext;
        public EspecialidadController(TurnosContext context) 
        { 
           _turnosContext = context;
        
        } 
        public async Task<IActionResult> Index()
        {
            return View(await _turnosContext.Especialidades.ToListAsync()); // Como un select * from
        }

        public async Task<IActionResult> Editar(int? Id)
        {
            if (Id == null ) 
            {
                return NotFound();
                
            }
            var Especialidad =await _turnosContext.Especialidades.FindAsync(Id); // Es como un select where
            if (Especialidad== null) 
            {
                return NotFound();
            }

            return View(Especialidad);

        }
        [HttpPost]
        public async Task<IActionResult> Editar(int? Id,[Bind("Id","Descripcion")] Especialidad especialidad)
        {   if (Id != especialidad.Id ) 
            {
                return NotFound();
            
            }
            if (ModelState.IsValid)
            {
                _turnosContext.Update(especialidad);
               await _turnosContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            } 
            return View(especialidad);
        }

        public async Task<IActionResult> Eliminar(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var especialidad =await _turnosContext.Especialidades.FirstAsync( x => x.Id == Id);  

            if (especialidad == null)
            {
                return NotFound();

            }
            return View(especialidad);
        }
        [HttpPost]
        public async Task<IActionResult> Eliminar(int Id)
        {
            var especialidad = await _turnosContext.Especialidades.FindAsync(Id);
            _turnosContext.Especialidades.Remove(especialidad); // como un delete from where
             await _turnosContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Crear()
        {
            return View();  
        }

        [HttpPost]
        public async Task<IActionResult> Crear([Bind("Id, Descripcion")] Especialidad especialidad)
        {
            if (ModelState.IsValid)
            {
                _turnosContext.Add(especialidad);
                await _turnosContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
      
    }
}

Turnos/Views/Especialidad/Crear.cshtml
@model Turnos.Models.Especialidad

<h4> Creacion Especialidad</h4>

<div>
    <form asp-action="Crear">
        <div class="row">       
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="input-field col s6">
                <i class="material-icons prefix">feed</i>
                <input asp-for="Descripcion" type="text" class="validate">
                <label asp-for="Descripcion"></label>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col s6 m2">
                <button asp-controller="Especialidad" asp-action="Crear" class="btn waves-effect waves-light" type="submit" name="action">
                    Crear
                    <i class="material-icons right">send</i>
                </button>
            </div>
            <div class=" col s6 m2">
                <a asp-action="Index" class="waves-effect waves-light btn"><i class="material-icons left">undo</i>Volver</a>
            </div>
        </div>

    </form>
</div>

Turnos/Views/Especialidad/Editar.cshtml
@model Turnos.Models.Especialidad

<h4>Edicion Especialidad</h4>

<div>
    <form asp-action="Editar">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="input-field col s6">
                <i class="material-icons prefix">feed</i>
                <input asp-for="Descripcion" type="text" class="validate">
                <label asp-for="Descripcion"></label>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col s6 m2">
                <button asp-controller="Especialidad" asp-action="Editar" class="btn waves-effect waves-light" type="submit" name="action">
                    Editar
                    <i class="material-icons right">send</i>
                </button>
            </div>
            <div class=" col s6 m2">
                <a asp-action="Index" class="waves-effect waves-light btn"><i class="material-icons left">undo</i>Volver</a>
            </div>
        </div>

    </form>
</div>

Turnos/Views/Especialidad/Eliminar.cshtml
@model Turnos.Models.Especialidad

<h3>Eliminacion de Especialidad</h3>
<div>
    <div class="row">
        <div class="col s12 m6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title"><h5><b>Descripcion de la Especialidad</b></h5> </span>
                    <p>
                        @Html.DisplayNameFor(model => model.Descripcion) :  @Html.DisplayFor(model => model.Descripcion)
                       
                    </p>
                </div>
                <div class="card-action blue-grey darken-2">
                    <form asp-action="Eliminar">
                        <input type="hidden" asp-for="Id" />
                        <input class="waves-effect waves-light btn red lighten-1" type="submit" value="Eliminar" />
                        <a class="right" asp-action="Index">Volver</a>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>

</div>

Turnos/Views/Especialidad/Index.cshtml
@model IEnumerable<Turnos.Models.Especialidad>
<p>
    <a class="btn-floating" asp-action="Crear"> <i class="material-icons">library_add</i> </a>
</p>
<html>
    <head>
        <title >Especialidad</title>
    </head>
    <body>

            <h1>Especialidades</h1>
            <div class="row">
                <table class="responsive-table highlight">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                </td>
                                 <td class="col s6">
                                    <a asp-action="Editar" asp-route-id="@item.Id"><i class="material-icons">edit_square</i></a> 
                                    <a asp-action="Eliminar" asp-route-id="@item.Id"><i class="material-icons red-text">delete_forever</i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
           </div>
    </body>
</html>