Turnos/Models/Medico.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Turnos.Models
{
    public class Medico
    {
        [Key]
        public int IdMedico { get; set; }

        [Required(ErrorMessage =("Debe Ingresar Un Nombre")),MaxLength(50),Unicode(false),Display(Name ="Nombre")]
        public string? NombreMedico { get; set; }

        [Required(ErrorMessage = ("Debe Ingresar Un Apellido")), MaxLength(50), Unicode(false), Display(Name ="Apellido")]
        public string? ApellidoMedico { get; set; }

        [Required(ErrorMessage = ("Debe Ingresar Una Direccion")), MaxLength(250), Unicode(false), Display (Name ="Direccion")]
        public string? DireccionMedico { get; set; }

        [Required(ErrorMessage = ("Debe Ingresar Una Direccion")), MaxLength(50), Unicode(false)]
        [EmailAddress]
        public string? Email { get; set; }

        [Required(ErrorMessage = ("Debe Ingresar Un Horario")), Unicode(false), Display(Name ="Hora de Atencion Inicial")]
        public DateTime HorarioAtencioDesde { get; set; }

        [Required(ErrorMessage = ("Debe Ingresar Un Horario")), Unicode(false), Display(Name ="Hora de Atencion Final")]
        public DateTime HorarioAtencioHasta { get; set; }
        public List<MedicoEspecialidad>? MedicoEspecialidad { get; set; }
        public List<Turno>? Turnos { get; set; }
    }
}

Turnos/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Turnos.Models;

namespace Turnos.Controllers
{
    public class MedicoController : Controller
    {
        private readonly TurnosContext _context;

        public MedicoController(TurnosContext context)
        {
            _context = context;
        }

        // GET: Medico
        public async Task<IActionResult> Index()
        {
              return _context.Medicos != null ? 
                          View(await _context.Medicos.ToListAsync()) :
                          Problem("Entity set 'TurnosContext.Medicos'  is null.");
        }

        // GET: Medico/Details/5
        public async Task<IActionResult> Detalles(int? id)
        {
            if (id == null || _context.Medicos == null)
            {
                return NotFound();
            }

            var medico = await _context.Medicos
                .Where(m => m.IdMedico == id).Include(me => me.MedicoEspecialidad)
                .ThenInclude(e => e.especialidades).FirstOrDefaultAsync();
            if (medico == null)
            {
                return NotFound();
            }

            return View(medico);
        }

        // GET: Medico/Create
        public IActionResult Crear()
        {
            ViewData["ListaEspecialidades"] = new SelectList(_context.Especialidades, "Id", "Descripcion");
            return View();

        }

        // POST: Medico/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear([Bind("IdMedico,NombreMedico,ApellidoMedico,DireccionMedico" +
            ",Email,HorarioAtencioDesde,HorarioAtencioHasta")] Medico medico, int Id)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medico);
                await _context.SaveChangesAsync();

                var medicoespecialidad = new MedicoEspecialidad();

                medicoespecialidad.IdMedico = medico.IdMedico;
                medicoespecialidad.IdEspecialidad = Id;

                _context.Add(medicoespecialidad);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(medico);
        }

        // GET: Medico/Edit/5
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.Medicos == null)
            {
                return NotFound();
            }

            var medico = await _context.Medicos.Where(m => m.IdMedico == id).
                Include(me => me.MedicoEspecialidad).FirstOrDefaultAsync();
            if (medico == null)
            {
                return NotFound();
            }
            ViewData["listaEspecialidades"] = new SelectList(_context.Especialidades, "Id", "Descripcion", 
                medico.MedicoEspecialidad[0].IdEspecialidad);
            return View(medico);
        }

        // POST: Medico/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Editar(int id, [Bind("IdMedico,NombreMedico,ApellidoMedico,DireccionMedico,Email,HorarioAtencioDesde," +
            "HorarioAtencioHasta")] Medico medico, int IdEspecialidad)
        {
            if (id != medico.IdMedico)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medico);
                    await _context.SaveChangesAsync();

                    var medicoEspecialidad = await _context.MedicoEspecialidad
                        .FirstOrDefaultAsync(me => me.IdMedico == id);

                     _context.Remove(medicoEspecialidad);
                    await _context.SaveChangesAsync();

                    medicoEspecialidad.IdEspecialidad = IdEspecialidad;
                    
                     _context.Add(medicoEspecialidad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicoExists(medico.IdMedico))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medico);
        }

        // GET: Medico/Delete/5
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.Medicos == null)
            {
                return NotFound();
            }

            var medico = await _context.Medicos
                .FirstOrDefaultAsync(m => m.IdMedico == id);
            if (medico == null)
            {
                return NotFound();
            }

            return View(medico);
        }

        // POST: Medico/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Confirmacioneliminacion(int id)
        {
            var medicoEspecialidad = await _context.MedicoEspecialidad
                .FirstOrDefaultAsync(me => me.IdMedico == id);

            _context.MedicoEspecialidad.Remove(medicoEspecialidad);
            await _context.SaveChangesAsync();

            if (_context.Medicos == null)
            {
                return Problem("Entity set 'TurnosContext.Medicos'  is null.");
            }
            var medico = await _context.Medicos.FindAsync(id);
            if (medico != null)
            {
                _context.Medicos.Remove(medico);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicoExists(int id)
        {
          return (_context.Medicos?.Any(e => e.IdMedico == id)).GetValueOrDefault();
        }

        public string TraerHorarioDesde(int IdMedico)
        {
            var HorarioDesde = _context.Medicos.Where(m => m.IdMedico == IdMedico).FirstOrDefault().HorarioAtencioDesde;

            return HorarioDesde.Hour + ":" + HorarioDesde.Minute;
        }
        public string TraerHorarioHasta(int IdMedico)
        {
            var HorarioHasta = _context.Medicos.Where(m => m.IdMedico == IdMedico).FirstOrDefault().HorarioAtencioHasta;

            return HorarioHasta.Hour + ":" + HorarioHasta.Minute;
        }
    }
}

Turnos/Views/Medico/Crear.cshtml
@model Turnos.Models.Medico


<h1>Nuevo Registro de Medico</h1>
<hr />
<div class="row">
    <div>
        <form class="col s8" asp-action="Crear">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input asp-for="NombreMedico" type="text" class="validate">
                    <label asp-for="NombreMedico"> Nombre</label>
                    <span asp-validation-for="NombreMedico" class="text-danger"></span>
                </div>
                <div class="input-field col s6">
                    <input asp-for ="ApellidoMedico" type="text" class="validate">
                    <label asp-for ="ApellidoMedico">Apellido</label>
                    <span asp-validation-for="ApellidoMedico" class="text-danger"></span>
                </div>
                <div class="input-field col s12">
                    <i class="material-icons prefix">markunread_mailbox</i>
                    <input asp-for="DireccionMedico" type="text" class="validate">
                    <label asp-for="DireccionMedico">Direccion</label>
                    <span asp-validation-for="DireccionMedico" class="text-danger"></span>
                </div>
                <div class="input-field col s12">
                    <i class="material-icons prefix">local_post_office</i>
                    <input asp-for="Email" type="text" class="validate">
                    <label asp-for="Email"></label>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="input-field col s12">
                    <i class="material-icons prefix">event_note</i>
                    <input asp-for="HorarioAtencioDesde" type="text" class="timepicker">
                    <label asp-for="HorarioAtencioDesde"></label>
                    <span asp-validation-for="HorarioAtencioDesde" class="text-danger"></span>
                </div>
                <div class="input-field col s12">
                    <i class="material-icons prefix">event_note</i>
                    <label asp-for="HorarioAtencioHasta" class=""></label>
                    <input asp-for="HorarioAtencioHasta" type="text" class="timepicker">
                    <span asp-validation-for="HorarioAtencioHasta" class="text-danger"></span>
                </div>
                <div class="input-field col s12">
                    <label class=""></label>
                    <select name="Id" class="" asp-items="ViewBag.ListaEspecialidades"></select>
                </div>
                <div class="row">
                    <div class="col s6 m6">
                        <button asp-controller="Medico" asp-action="Crear" class="btn waves-effect waves-light" type="submit" name="action">
                            Crear
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                    <div class=" col s6 m6">
                        <a asp-action="Index" class="waves-effect waves-light btn"><i class="material-icons left">undo</i>Volver</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Turnos/Views/Medico/Detalles.cshtml
@model Turnos.Models.Medico

@{
    ViewData["Title"] = "Details";
}

<h1 class="center">Detalles del Medico</h1>
<hr />
<div>
    <div class="row">
        <div class="col s12 m6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title"><h5><b>@Html.DisplayFor(model => model.NombreMedico), @Html.DisplayFor(model => model.ApellidoMedico)</b></h5> </span>
                    <p>
                        @Html.DisplayNameFor(model => model.DireccionMedico) :  @Html.DisplayFor(model => model.DireccionMedico)
                        <hr />
                        @Html.DisplayNameFor(model => model.Email) : @Html.DisplayFor(model => model.Email)
                        <hr />
                        @Html.DisplayNameFor(model => model.HorarioAtencioDesde) :  @Html.DisplayFor(model => model.HorarioAtencioDesde)
                        <hr />

                        @Html.DisplayNameFor(model => model.HorarioAtencioHasta) : @Html.DisplayFor(model => model.HorarioAtencioHasta)
                    </p>
                </div>
                <div class="card-action blue-grey darken-2">
                        <input type="hidden" asp-for="IdMedico" />
                       <a asp-action="Editar" asp-route-id="@Model.IdMedico">Editar</a>
                        <a class="right" asp-action="Index">Volver</a>
                   
                </div>
            </div>
        </div>
    </div>

</div>

Turnos/Views/Medico/Editar.cshtml
@model Turnos.Models.Medico

<h4 class="center">Edicion</h4>
<hr />
<div class="row">
    <div>
        <form class="col s8" asp-action="Editar" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdMedico" />
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <input asp-for="NombreMedico" type="text" class="validate">
                <label asp-for="NombreMedico"></label>
                <span asp-validation-for="NombreMedico" class="text-danger"></span>
            </div>
            <div class="input-field col s6">
                <input asp-for="ApellidoMedico" type="text" class="validate">
                <label asp-for="ApellidoMedico"></label>
                <span asp-validation-for="ApellidoMedico" class="text-danger"></span>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">markunread_mailbox</i>
                <input asp-for="DireccionMedico" type="text" class="validate">
                <label asp-for="DireccionMedico"></label>
                <span asp-validation-for="DireccionMedico" class="text-danger"></span>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">local_post_office</i>
                <input asp-for="Email" type="text" class="validate">
                <label asp-for="Email"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">event_note</i>
                <input asp-for="HorarioAtencioDesde" type="text" class="timepicker">
                <label asp-for="HorarioAtencioDesde"></label>
                <span asp-validation-for="HorarioAtencioDesde" class="text-danger"></span>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">event_note</i>
                <label asp-for="HorarioAtencioHasta" class=""></label>
                <input asp-for="HorarioAtencioHasta" type="text" class="timepicker">
                <span asp-validation-for="HorarioAtencioHasta" class="text-danger"></span>
            </div>
            <div class="input-field col s12 row">
                <label class=""></label>
                <select name="IdEspecialidad" class="" asp-items="ViewBag.ListaEspecialidades"></select>
            </div>
            <div class="col s6 m6">
                <button asp-controller="Medico" asp-action="Editar" class="btn waves-effect waves-light" type="submit" name="action">
                    Editar
                    <i class="material-icons right">send</i>
                </button>
            </div>
            <div class=" col s6 m6">
                <a asp-action="Index" class="waves-effect waves-light btn"><i class="material-icons left">undo</i>Volver</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Turnos/Views/Medico/Eliminar.cshtml
@model Turnos.Models.Medico

@{
    ViewData["Title"] = "Delete";
}

<h3>Quieres Eliminar Este Registro?</h3>
<div>
    <h4>Medico</h4>

    <div class="row">
        <div class="col s12 m6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title"><h5><b>@Html.DisplayFor(model => model.NombreMedico), @Html.DisplayFor(model => model.ApellidoMedico)</b></h5> </span>
                    <p>
                        @Html.DisplayNameFor(model => model.DireccionMedico) :  @Html.DisplayFor(model => model.DireccionMedico)
                        <hr />
                        @Html.DisplayNameFor(model => model.Email) : @Html.DisplayFor(model => model.Email)
                        <hr />
                        @Html.DisplayNameFor(model => model.HorarioAtencioDesde) :  @Html.DisplayFor(model => model.HorarioAtencioDesde)
                        <hr />

                        @Html.DisplayNameFor(model => model.HorarioAtencioHasta) : @Html.DisplayFor(model => model.HorarioAtencioHasta)
                    </p>
                </div>
                <div class="card-action blue-grey darken-2">
                    <form asp-action="Eliminar">
                        <input type="hidden" asp-for="IdMedico" />
                        <input class="waves-effect waves-light btn red" type="submit" value="Eliminar" />
                        <a class="right"  asp-action="Index">Volver</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
 
</div>

Turnos/Views/Medico/Index.cshtml
@model IEnumerable<Turnos.Models.Medico>

@{
    ViewData["Title"] = "Index";
}

<h1>Medico</h1>

<p>
    <a class="btn-floating" asp-action="Crear"> <i class="material-icons">person_add</i> </a>
</p>
<table class="responsive-table highlight">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreMedico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoMedico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DireccionMedico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HorarioAtencioDesde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HorarioAtencioHasta)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreMedico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoMedico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DireccionMedico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HorarioAtencioDesde)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HorarioAtencioHasta)
            </td>
            <td>
                    <a asp-action="Editar" asp-route-id="@item.IdMedico"><i class="material-icons">edit_square</i></a> |
                    <a asp-action="Detalles" asp-route-id="@item.IdMedico"><i class="material-icons yellow-text">more_vert</i></a> |
                    <a asp-action="Eliminar" asp-route-id="@item.IdMedico"><i class="material-icons red-text">delete_forever</i></a>
            </td>
        </tr>
}
    </tbody>
</table>